"""
Django settings for geodjango project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '67400^mh7)$an=9ql7y8o*9#wnp9+yk#_v_f@)4r(5oq^o-=^8'

#production



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',    #add this line
    'world',
    'leaflet',
    'djgeojson',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geodjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['world/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geodjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'postgis',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}

#CONFIGURE THESE PATH SETTINGS
GEOS_LIBRARY_PATH = 'C:/Users/User/PycharmProjects/geodjango/venv/Lib/site-packages/osgeo/geos_c.dll'
GDAL_LIBRARY_PATH = 'C:/Users/User/PycharmProjects/geodjango/venv/Lib/site-packages/osgeo/gdal300.dll'
GDAL_DATA = 'C:/Users/User/PycharmProjects/geodjango/venv/Lib/site-packages/osgeo/data/gdal'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#add the serializaion modules
SERIALIZATION_MODULES = {
    "geojson": "django.contrib.gis.serializers.geojson",
}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

#Deployment
#STATIC_ROOT = "/var/www/example.com/static/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

#manage media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# configure django-leaflet
LEAFLET_CONFIG = {
    #CONFIG HERE
    #'SPATIAL_EXTENT': (),
    'DEFAULT_CENTER': (0.76, 37.68),
    'DEFAULT_ZOOM': 6,
    'MIN_ZOOM': 0,
    'MAX_ZOOM': 18,
    'SPATIAL_EXTENT': (-180, -90, 180, 90),
    'ATTRIBUTION_PREFIX': 'Powered by django-leaflet',
    'NO_GLOBALS': False,
    'MINIMAP': False,
    'RESET_VIEW': False,

    'TILES': [('Esri_WorldTopoMap', 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}', {
	'attribution': 'Tiles &copy; Esri &mdash; Esri and the GIS User Community'
}),
              ('Stamen_Terrain','https://stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}{r}.{ext}', {
                'attribution': 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
                'subdomains': 'abcd',
                'minZoom': 0,
                'maxZoom': 18,
                'ext': 'png'
})],
}
