# Generated by Django 3.0.1 on 2020-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='prov',
            field=models.CharField(choices=[('CENTRAL', 'central'), ('COAST', 'coast'), ('EASTERN', 'eastern'), ('N.EASTERN', 'n.eastern'), ('NAIROBI', 'nairobi'), ('NYANZA', 'nyanza'), ('RIFT VALLEY', 'riftvalley'), ('WESTERN', 'western')], max_length=50, null=True),
        ),
    ]
